package com.ishaan.apcsa_compiler.errors;

/**
 * This enum represents each of the possible error types that can be encountered by the compiler.
 */
public enum ErrorKind {
    ILLEGAL_EOF_MULTILINE_COMMENT,
    ILLEGAL_OPERATOR_AMPERSAND,
    ILLEGAL_OPERATOR_BAR,
    ILLEGAL_CHAR_AFTER_NUMERIC_SEPARATOR,
    ILLEGAL_LONG_LITERAL,
    ILLEGAL_FLOAT_LITERAL,
    NUMERIC_SEPARATOR_AFTER_FLOATING_POINT,
    NO_DIGIT_AFTER_EXPONENT_INDICATOR,
    NO_HEX_DIGIT_AFTER_SPECIFIER,
    NO_HEX_DIGIT_AFTER_FLOATING_POINT,
    NO_HEX_DOUBLE_EXPONENT,
    ILLEGAL_HEX_LITERAL,
    ILLEGAL_BINARY_LITERALS,
    ILLEGAL_OCTAL_LITERAL,
    NO_FRACTION_PART_IN_OCTAL_TO_DOUBLE_LITERAL,
    ILLEGAL_CODEPOINT_CHAR_LITERAL,
    UNTERMINATED_CHAR_LITERAL,
    ILLEGAL_CHAR_LITERAL,
    ESCAPE_NOT_IN_SUBSET,
    INVALID_ESCAPE,
    INVALID_UNICODE_ESCAPE,
    UNTERMINATED_STRING_LITERAL,
    NEWLINE_IN_STRING_LITERAL
}
